/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.calculadoratarea;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.script.ScriptEngine;
import javax.swing.JOptionPane;

/**
 *
 * @author Reyner
 */
public class Calculadora extends javax.swing.JFrame {
    /**
     * Creates new form Calculadora
     */
    float number1, number2; // variables para los dos numeros ingresados
    String sign; // variable para almacenar el signo de operacion
   
    
    public Calculadora() {
        initComponents();
        jPanel1.setBackground(new Color(30,30,30)); //Establece el color de fondo de ventana
        jPanel2.setBackground(new Color(30,30,30));    
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Label_Calc = new javax.swing.JLabel();
        Label_Result = new javax.swing.JLabel();
        Label_Info = new javax.swing.JLabel();
        Label_Info2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Button_Menu = new javax.swing.JButton();
        Button_8 = new javax.swing.JButton();
        Button_Delete = new javax.swing.JButton();
        Button_7 = new javax.swing.JButton();
        Button_Comma = new javax.swing.JButton();
        Button_9 = new javax.swing.JButton();
        Button_4 = new javax.swing.JButton();
        Button_5 = new javax.swing.JButton();
        Button_6 = new javax.swing.JButton();
        Button_Division = new javax.swing.JButton();
        Button_Multiply = new javax.swing.JButton();
        Button_Minus = new javax.swing.JButton();
        Button_2 = new javax.swing.JButton();
        Button_1 = new javax.swing.JButton();
        Button_3 = new javax.swing.JButton();
        Button_Plus = new javax.swing.JButton();
        Button_Equal = new javax.swing.JButton();
        Button_0 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Label_Calc.setBackground(new java.awt.Color(204, 204, 204));
        Label_Calc.setFont(new java.awt.Font("Segoe UI Variable", 0, 18)); // NOI18N
        Label_Calc.setForeground(new java.awt.Color(255, 255, 255));
        Label_Calc.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        Label_Result.setBackground(new java.awt.Color(255, 255, 255));
        Label_Result.setFont(new java.awt.Font("Segoe UI Variable", 1, 42)); // NOI18N
        Label_Result.setForeground(new java.awt.Color(255, 255, 255));
        Label_Result.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        Label_Info.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        Label_Info.setForeground(new java.awt.Color(255, 255, 255));

        Label_Info2.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        Label_Info2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_Info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Label_Info2, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(Label_Calc, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Label_Result, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Label_Calc, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(Label_Result, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Label_Info, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Label_Info2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 30, Short.MAX_VALUE))
        );

        jPanel2.setForeground(new java.awt.Color(30, 30, 30));

        Button_Menu.setBackground(new java.awt.Color(102, 102, 102));
        Button_Menu.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        Button_Menu.setForeground(new java.awt.Color(255, 255, 255));
        Button_Menu.setText("RULES");
        Button_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_MenuActionPerformed(evt);
            }
        });

        Button_8.setBackground(new java.awt.Color(102, 102, 102));
        Button_8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Button_8.setForeground(new java.awt.Color(255, 255, 255));
        Button_8.setText("8");
        Button_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_8ActionPerformed(evt);
            }
        });

        Button_Delete.setBackground(new java.awt.Color(102, 102, 102));
        Button_Delete.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        Button_Delete.setForeground(new java.awt.Color(255, 255, 255));
        Button_Delete.setText("DEL");
        Button_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_DeleteActionPerformed(evt);
            }
        });

        Button_7.setBackground(new java.awt.Color(102, 102, 102));
        Button_7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Button_7.setForeground(new java.awt.Color(255, 255, 255));
        Button_7.setText("7");
        Button_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_7ActionPerformed(evt);
            }
        });

        Button_Comma.setBackground(new java.awt.Color(102, 102, 102));
        Button_Comma.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Button_Comma.setForeground(new java.awt.Color(255, 255, 255));
        Button_Comma.setText(".");
        Button_Comma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_CommaActionPerformed(evt);
            }
        });

        Button_9.setBackground(new java.awt.Color(102, 102, 102));
        Button_9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Button_9.setForeground(new java.awt.Color(255, 255, 255));
        Button_9.setText("9");
        Button_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_9ActionPerformed(evt);
            }
        });

        Button_4.setBackground(new java.awt.Color(102, 102, 102));
        Button_4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Button_4.setForeground(new java.awt.Color(255, 255, 255));
        Button_4.setText("4");
        Button_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_4ActionPerformed(evt);
            }
        });

        Button_5.setBackground(new java.awt.Color(102, 102, 102));
        Button_5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Button_5.setForeground(new java.awt.Color(255, 255, 255));
        Button_5.setText("5");
        Button_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_5ActionPerformed(evt);
            }
        });

        Button_6.setBackground(new java.awt.Color(102, 102, 102));
        Button_6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Button_6.setForeground(new java.awt.Color(255, 255, 255));
        Button_6.setText("6");
        Button_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_6ActionPerformed(evt);
            }
        });

        Button_Division.setBackground(new java.awt.Color(102, 102, 102));
        Button_Division.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Button_Division.setForeground(new java.awt.Color(255, 255, 255));
        Button_Division.setText("/");
        Button_Division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_DivisionActionPerformed(evt);
            }
        });

        Button_Multiply.setBackground(new java.awt.Color(102, 102, 102));
        Button_Multiply.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Button_Multiply.setForeground(new java.awt.Color(255, 255, 255));
        Button_Multiply.setText("*");
        Button_Multiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_MultiplyActionPerformed(evt);
            }
        });

        Button_Minus.setBackground(new java.awt.Color(102, 102, 102));
        Button_Minus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Button_Minus.setForeground(new java.awt.Color(255, 255, 255));
        Button_Minus.setText("-");
        Button_Minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_MinusActionPerformed(evt);
            }
        });

        Button_2.setBackground(new java.awt.Color(102, 102, 102));
        Button_2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Button_2.setForeground(new java.awt.Color(255, 255, 255));
        Button_2.setText("2");
        Button_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_2ActionPerformed(evt);
            }
        });

        Button_1.setBackground(new java.awt.Color(102, 102, 102));
        Button_1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Button_1.setForeground(new java.awt.Color(255, 255, 255));
        Button_1.setText("1");
        Button_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_1ActionPerformed(evt);
            }
        });

        Button_3.setBackground(new java.awt.Color(102, 102, 102));
        Button_3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Button_3.setForeground(new java.awt.Color(255, 255, 255));
        Button_3.setText("3");
        Button_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_3ActionPerformed(evt);
            }
        });

        Button_Plus.setBackground(new java.awt.Color(102, 102, 102));
        Button_Plus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Button_Plus.setForeground(new java.awt.Color(255, 255, 255));
        Button_Plus.setText("+");
        Button_Plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_PlusActionPerformed(evt);
            }
        });

        Button_Equal.setBackground(new java.awt.Color(153, 36, 65));
        Button_Equal.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        Button_Equal.setForeground(new java.awt.Color(255, 255, 255));
        Button_Equal.setText("=");
        Button_Equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_EqualActionPerformed(evt);
            }
        });

        Button_0.setBackground(new java.awt.Color(102, 102, 102));
        Button_0.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Button_0.setForeground(new java.awt.Color(255, 255, 255));
        Button_0.setText("0");
        Button_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_0ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Button_Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button_7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Button_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Button_0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(Button_3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Button_Plus, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Button_Equal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Button_8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Button_5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Button_Delete, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(Button_6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Button_9, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                    .addComponent(Button_Comma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Button_Division, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Button_Multiply, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                .addComponent(Button_Minus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_Comma, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_Division, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Button_Multiply, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Button_7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Button_8, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Button_9, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_Minus, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_Plus, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Button_0, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_Equal, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
// Se llama al metodo para agregar numeros o signos segun corresponda en cada caso
    private void Button_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_7ActionPerformed
        
        AddDigits ("7");
        
    }//GEN-LAST:event_Button_7ActionPerformed

    private void Button_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_8ActionPerformed
        
        AddDigits ("8");
    }//GEN-LAST:event_Button_8ActionPerformed

    private void Button_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_6ActionPerformed
        
        AddDigits ("6");
    }//GEN-LAST:event_Button_6ActionPerformed

    private void Button_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_MenuActionPerformed
        
        JOptionPane.showMessageDialog(null,"- No se puede dividir entre 0\n - Unicamente realizar operaciones entre dos numeros\n\n\n - Author: Reyner");
    }//GEN-LAST:event_Button_MenuActionPerformed

    private void Button_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_0ActionPerformed
        
       AddDigits ("0");
    }//GEN-LAST:event_Button_0ActionPerformed

    private void Button_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_1ActionPerformed

        AddDigits ("1");
    }//GEN-LAST:event_Button_1ActionPerformed

    private void Button_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_2ActionPerformed
        
        AddDigits ("2");
    }//GEN-LAST:event_Button_2ActionPerformed

    private void Button_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_3ActionPerformed
        
        AddDigits ("3");
    }//GEN-LAST:event_Button_3ActionPerformed

    private void Button_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_4ActionPerformed
        
        AddDigits ("4");
    }//GEN-LAST:event_Button_4ActionPerformed

    private void Button_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_5ActionPerformed
        
        AddDigits ("5");
    }//GEN-LAST:event_Button_5ActionPerformed

    private void Button_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_9ActionPerformed
        
        AddDigits ("9");
    }//GEN-LAST:event_Button_9ActionPerformed

    private void Button_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_DeleteActionPerformed
        
        Label_Result.setText(""); // Limpia la pantalla en el label de numeros grandes
        Label_Calc.setText(""); // Limpia la pantalla en el label de numeros pequeños
        
        // Establece que los botones sean visibles luego de clickear el boton para limpiar pantalla
        // Esto es importante para que asi el usuario pueda digitar otra operacion distinta
        Button_Plus.setEnabled(true);
        Button_Minus.setEnabled(true);
        Button_Division.setEnabled(true);
        Button_Multiply.setEnabled(true);
    }//GEN-LAST:event_Button_DeleteActionPerformed

    private void Button_DivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_DivisionActionPerformed
        
        number1 = Float.parseFloat(Label_Result.getText()); // Convierte el numero en texto
        sign="/"; // Se le asigna el signo de division
         Label_Result.setText(""); // Limpia el label grande para que no se vean juntos los numeros
         Label_Calc.setText(Label_Calc.getText()+" / "); // Se escribe el signo correspondiente a la operacion en el label pequeño 
         
         // Establece todos los botones de operaciones en falso para que solo se pueda hacer una operacion entre dos numeros
       Button_Plus.setEnabled(false);
       Button_Minus.setEnabled(false);
       Button_Multiply.setEnabled(false);
       Button_Division.setEnabled(false);
    }//GEN-LAST:event_Button_DivisionActionPerformed

    private void Button_MultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_MultiplyActionPerformed
        
        number1 = Float.parseFloat(Label_Result.getText());
        sign="*";
         Label_Result.setText("");
        Label_Calc.setText(Label_Calc.getText()+" * ");
        
       Button_Plus.setEnabled(false);
       Button_Minus.setEnabled(false);
       Button_Multiply.setEnabled(false);
       Button_Division.setEnabled(false);
    }//GEN-LAST:event_Button_MultiplyActionPerformed

    private void Button_MinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_MinusActionPerformed
       
        number1 = Float.parseFloat(Label_Result.getText());
        sign="-";
         Label_Result.setText("");
        Label_Calc.setText(Label_Calc.getText()+" - ");
        
       Button_Plus.setEnabled(false);
       Button_Minus.setEnabled(false);
       Button_Multiply.setEnabled(false);
       Button_Division.setEnabled(false);
    }//GEN-LAST:event_Button_MinusActionPerformed

    private void Button_PlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_PlusActionPerformed
        
        number1 = Float.parseFloat(Label_Result.getText());
        sign="+";
        Label_Result.setText("");
       Label_Calc.setText(Label_Calc.getText()+" + ");
       
       Button_Plus.setEnabled(false);
       Button_Minus.setEnabled(false);
       Button_Multiply.setEnabled(false);
       Button_Division.setEnabled(false);
    }//GEN-LAST:event_Button_PlusActionPerformed

    private void Button_EqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_EqualActionPerformed
     
             
             number2 = Float.parseFloat(Label_Result.getText()); // Combierte el segundo numero
              Label_Calc.setText(Label_Calc.getText()+" = "); // Se muestra el signo de igualacion en el Label pequeño
         
              // Logica de operaciones segun cada caso
             switch(sign){
                 case "+":
                     Label_Result.setText(Float.toString(number1+number2)); // Suma los dos numeros
                     break;
                 case "-":
                     Label_Result.setText(Float.toString(number1-number2)); // Resta los dos numeros
                     break;
                 case "*":
                     Label_Result.setText(Float.toString(number1*number2)); // Multiplica los dos numeros
                     break;
                 case "/": // Divide los dos numeros
                     if(number2 == 0){   // Limita al usuario a que no se puedan hacer divisiones entre 0
                     Label_Result.setText("MATH ERROR");
                     }else{
                         Label_Result.setText(Float.toString(number1/number2));
                     }
                     break;
         }
    }//GEN-LAST:event_Button_EqualActionPerformed

    private void Button_CommaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_CommaActionPerformed

        AddDigits (".");
    }//GEN-LAST:event_Button_CommaActionPerformed
public void AddDigits(String digit){ //Se agrega un numero segun el click de un boton
    Label_Result.setText(Label_Result.getText()+digit);
     Label_Calc.setText(Label_Calc.getText()+digit);
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_0;
    private javax.swing.JButton Button_1;
    private javax.swing.JButton Button_2;
    private javax.swing.JButton Button_3;
    private javax.swing.JButton Button_4;
    private javax.swing.JButton Button_5;
    private javax.swing.JButton Button_6;
    private javax.swing.JButton Button_7;
    private javax.swing.JButton Button_8;
    private javax.swing.JButton Button_9;
    private javax.swing.JButton Button_Comma;
    private javax.swing.JButton Button_Delete;
    private javax.swing.JButton Button_Division;
    private javax.swing.JButton Button_Equal;
    private javax.swing.JButton Button_Menu;
    private javax.swing.JButton Button_Minus;
    private javax.swing.JButton Button_Multiply;
    private javax.swing.JButton Button_Plus;
    private javax.swing.JLabel Label_Calc;
    private javax.swing.JLabel Label_Info;
    private javax.swing.JLabel Label_Info2;
    private javax.swing.JLabel Label_Result;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
